### ISSUE TITLE
Need basic installation documentation

### ISSUE THREAD

**Issue by ankitmundra88** [dlundgren/phagrancy#4]
@dlundgren 

We are trying to install the phagrancy on Oracle Linux 6. We have been able to host the application but are not able to check whether it is properly running or not.
Can we have a documentation that would provide us with the information on what httpd.conf we would need to host the application correctly. 

Also the curl command provided in the readme.md are incorrect. As the httpd is hosted on port 80 and not port 8099. 

Having a basic documentation stating what needs to be placed where and what configuration should be done for apache would help a lot. 

Thanks for building the application though. :-)

**Comment by mclamb** [comment]
Agreed, this project is exactly what I am looking for but having some issues getting it up and running. I am currently trying to get phagrancy running with the following docker-compose file:

```
version: '2'

services:
  nginx-php-fpm:
    image: richarvey/nginx-php-fpm:latest
    restart: always
    environment:
      GIT_REPO: 'https://github.com/dlundgren/phagrancy.git'
      WEBROOT: '/var/www/html/web'
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      no_proxy: ${no_proxy}
```

The process is not fully automated yet in docker-compose until I can figure out all the steps necessary, but for now, I run the above (```docker-compse up```) and then ```docker exec -it <container> /bin/bash``` in another shell so that I can install php composer, dependency modules, .env, etc:

```
# Get php composer
cd /root
wget -O composer-setup.php https://getcomposer.org/installer
php composer-setup.php --install-dir=/usr/local/bin --filename=composer

# Install phagrancy dependencies with composer
cd /var/www/html
composer install

# Create sample .env file, I think the "access_password" is the name of the user?
cat > .env <<EOF
storage_path="data/storage"
api_token="mytoken"
access_password="myuser"
EOF

# Create /var/www/html/data/storage (eventually will move this to a persistent docker volume)
mkdir -p data/storage

# Restart php-fpm? Is this necessary?
supervisorctl restart php-fpm
```

At this point things are running and I can see the web requests in the docker-compose output. If I try something like this within the container shell:

```
cd /root
# Just create a dummy file that represents a box for now
echo random string > testbox.box
curl -XPUT http://localhost/api/v1/box/myuser/testbox/version/1.0.0/provider/virtualbox/upload --upload-file testbox.box
```

The request does not seem to work. I get a 404 page back. I was thinking that this should upload that dummy test box into data/storage/myuser/testbox/ or something like that?

Any suggestions would be much appreciated!

Thanks
